name: Build kmods

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 12 * * *'  # 6:00 PM Dhaka time (UTC+6) everyday
  pull_request:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    name: Build kmods
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora-release: [40, 41]  # Add Fedora releases here
        kmod-name: [nvidia]

    env:
      IMAGE_NAME: akmods/${{ matrix.kmod-name }}
      FEDORA_RELEASE: ${{ matrix.fedora-release }}

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Image Metadata
        id: generate-meta
        shell: bash
        run: |
          tags=()
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.fedora-release }}")
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.fedora-release }}-$(date +%Y%m%d%H%M%S)")
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.fedora-release }}-${GITHUB_SHA::7}")

          echo "tags=${tags[*]}" >> $GITHUB_OUTPUT
          concat_tags=$(IFS=, ; echo "${tags[*]}")
          echo "concat_tags=$concat_tags" >> $GITHUB_OUTPUT

      - name: Fetch akmods signing key
        run: |
          echo "${{ secrets.AKMODS_PRIVATE_KEY }}" > certs/private_key.priv

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          file: ./Containerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.generate-meta.outputs.concat_tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            KMOD_NAME=${{ matrix.kmod-name }}
            FEDORA_RELEASE=${{ matrix.fedora-release }}

  check:
    needs: [build]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Exit on failure
        if: ${{ needs.build.result == 'failure' }}
        run: exit 1

      - name: Exit on success
        run: exit 0
